version: '2.1'
services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=turing
    - MYSQL_USER=turing
    - MYSQL_PASSWORD=turing