version: '2.1'
services:
  # api:
  #   container_name: api
  #   build: .
  #   environment:
  #     SECRET: sloth
  #     DB_URL: "192.168.99.100"
  #     DB_USER: turing
  #     DB_PASSWORD: turing
  #     DB_NAME: turing
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - mysql
  mysql:
    container_name: mysql
    image: mysql:5.6
    ports:
       - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=turing
      - MYSQL_USER=turing
      - MYSQL_PASSWORD=turing
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_DEV_ROOT_TOKEN_ID: "sloths-are-nice"
    volumes:
      - ./file:/vault/file:rw
      - ./config:/vault/config:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4567-4580:4567-4580
    environment:
      - SERVICES=s3