version: '2.1'
services:
  # api:
  #   container_name: api
  #   build: .
  #   environment:
  #     SECRET: sloth
  #     DB_URL: "192.168.99.100"
  #     DB_USER: turing
  #     DB_PASSWORD: turing
  #     DB_NAME: turing
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: turing
    ports:
      - 27017:27017
    volumes:
       - ./data/db:/data
       - ./mongo_docker:/docker-entrypoint-initdb.d
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4567-4580:4567-4580
    environment:
      - SERVICES=s3    